### ISSUE TITLE
Support Apple Silicon in lldb

### ISSUE THREAD

**Issue by mateka** [daveleroy/sublime_debugger#109]
It would be nice to support Apple Silicon on new Macs. There is an open issue in vscode-lldb for this: https://github.com/vadimcn/vscode-lldb/issues/397.

**Comment by daveleroy** [comment]
Can you run `import platform; platform.machine()` in the sublime console and give me the output?

In the mean time you can use the pre-release versions by manually installing them https://github.com/vadimcn/vscode-lldb/releases. Download the codelldb-aarch64-darwin.vsix rename to .zip and unzip it and replace Packages/Debugger/data/adapters/lldb/extension with the extension folder inside the zip file

**Comment by mateka** [comment]
Yes, of course, I can. Here it is:
```
>>> import platform; platform.machine()
'arm64'
```
I've already unpacked the prerelease version of vscode-lldb into my plugins folder and it almost works like a charm (it complains about initializing Python visualizers). I could do a pull request if it is ok, that it will work when the stable version of vscode-lldb will handle M1 chips.

**Comment by daveleroy** [comment]
Of course if you have time for it. Otherwise I can do it this weekend.

These are the relevant files.
https://github.com/daveleroy/sublime_debugger/blob/master/modules/core/platform.py
https://github.com/daveleroy/sublime_debugger/blob/81bc945c7763239b9b22567972821194ec16e6f5/modules/adapters/lldb.py#L85

**Comment by mateka** [comment]
I've done a pull request.
