### ISSUE TITLE
Virtual environments

### ISSUE THREAD

**Issue by sschuhmann** [daveleroy/sublime_debugger#112]
Thanks for developing this plugin!

I use pipenv and virtual environment in my Python development workflow, which can be used by various Sublime Plugins. However, I have not been able to use (at best automatically) the associated virtual environment for debugging, which often leads to missing dependencies. 
Is there any way to utilize virtual environments in this plugin?

**Comment by daveleroy** [comment]
I'm not entirely sure how virtual environments are supposed to work with debugpy .

I believe you probably just need debugpy to be started using the virtual env python instead of the system one. Adding `pythonPath` to your configuration might work (only supported in the st4 version).

Something like this might work.
```
{
   "pythonPath": "${project_folder}/.venv/bin/python"
}
```

**Comment by meengit** [comment]
Hi @sschuhmann and @daveleroy 

For [FastAPI](https://github.com/tiangolo/fastapi) in a [Pipenv](https://github.com/pypa/pipenv) environment, I'm using this setting:

```javascript
// SublimeText Build 4105, Apple MacOS 11.3.1
"debugger_configurations":
[
  {
    "name": "Python: Debug FastAPI (launch)",
    "type": "python",
    "request": "launch",
    "console": "integratedTerminal",
    "cwd": "/absolute/path/to/project/root",
    "python": "/absolute/path/to/virtualenv/bin/python", // see "pipenv --venv"
    "program": "/absolute/path/to/virtualenv/bin/uvicorn",
    "args": [
      "app.main:app" // FastAPI application
    ]
  }
]
```

Since I use these settings, I haven't any issues. If you also use FastAPI, please have a look [here](https://blog.hanchon.live/tips/debug-fastapi-app-with-vscode/) as well.

**Comment by daveleroy** [comment]
@meengit Thanks for sharing this.

Not sure how I missed the `python` option its listed here https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings

It should work in the st3 version as well.
