### ISSUE TITLE
Java adaptor.

### ISSUE THREAD

**Issue by arshappleid** [daveleroy/sublime_debugger#118]
I cannot seem to set this up for java, I have used vs code debugger for java, and therefore copied over my vscode java configuration. Also I am use ST4. For some reason the package control file did not seem to work at all, so I downloaded the one from the git main page, but now I have double Debugger options in my menu bar.

1. I created a sublime project , and saved my configurations there.
2.  Put breakpoint in a perfectly fine java program , and tried to debug it.
- Also I installed adaptors but only for python, since it is the other language I know.
-

Here are my vs code configurations for java.
![image](https://user-images.githubusercontent.com/68478842/120667680-5b96e700-c4ab-11eb-8805-414b460b58fd.png)
I removed the jdk path , and the debugger still will not work.
I think the main problem is I do not have an adaptor installed for java.

It says cannot find the adaptor.

It would be nice to have this working, I really do not like vs code , but need it for the debugger (60% of my coding).  Also if someone could tell me if I made any mistakes in my setup, that will be great.

I am getting this error in the terminal.
![image](https://user-images.githubusercontent.com/68478842/120687609-c94d0e00-c4bf-11eb-8746-7c9c273df93a.png)

**Comment by daveleroy** [comment]
There isn't support for a java adapter yet. 

There is some initial stuff to support the java debug adapter supplied by jdtls here https://github.com/daveleroy/sublime_debugger/pull/106 which requires LSP-jdtls to be running and has not been finished yet. Because of the way the java debug adapter is setup it is not friendly and easy to integrate like many of the other debug adapters out there.

**Comment by arshapplied** [comment]
Okay thanks for letting me know. Do you have a timeline, on when you think it might be done , on your side. Also do you think when it is done, you can upload it to the package control website for Sublime text. It will be great to keep checking over there. 
It would help new developers a lot, since java is more of a beginners language.
Thanks for your work on the debugger though.
