### ISSUE TITLE
UI broken in latest dev builds (4122)

### ISSUE THREAD

**Issue by rchl** [daveleroy/sublime_debugger#129]
The layout is kinda broken, with no variables pane visible (or misplaced)

<img width="1440" alt="Screenshot 2021-11-14 at 10 36 12" src="https://user-images.githubusercontent.com/153197/141676450-06492b36-e62f-47f5-8d7e-9fda9a725298.png">

**Comment by rchl** [comment]
Will also ask maybe related question here. Is the `Terminal` view supposed to be scrollable?

<img width="1020" alt="Screenshot 2021-11-14 at 12 44 38" src="https://user-images.githubusercontent.com/153197/141679410-6830061e-0802-4727-aa0c-b11aa32bdce3.png">

I can't access the beginning of the error right now.

Also worth noticing that the whole panel is scrollable (intended) but it doesn't help for this case.

**Comment by daveleroy** [comment]
@rchl regarding the issues with the terminal. For now you can click on the tab when its already open and it will open the terminal in an output panel.

I have tried a bunch of things to get an integrated terminal working nicely and scrollable and just cannot do it inside a phantom. No way to copy stuff really sucks as well.

I have been slowly working on replacing the integrated terminals with a view that appears when you are debugging and gets removed when you click away from it after debugging. This works great for me since I have a really wide monitor but probably isn't going to be all that great for smaller screens. Probably still better than the phantom approach.

<img width="2016" alt="Screen Shot 2021-11-14 at 11 13 17 AM" src="https://user-images.githubusercontent.com/2889367/141695096-a4369e2b-0796-4412-bbbe-0d4f5316c120.png">


> Also worth noticing that the whole panel is scrollable (intended?) but it doesn't help for this case.

Scrolling is intended and it's useful for the other panels since they expand downwards when they have lots of content. Unfortunately not so useful in the case of a terminal.
