### ISSUE TITLE
Any way to connect directly?

### ISSUE THREAD

**Issue by MetalSlime0** [daveleroy/sublime_debugger#191]
I'm making a language that supports the DAP directly - like, you can just connect to the executable running the code on a local port and start sending DAP messages. Is there any kind of "passthrough" adapter that would do this? (Obviously it would only support "attach" and not "launch".) If not, is it easy to make?

**Comment by daveleroy** [comment]
Make an `AdapterConfiguration` for it like all the other adapters it should be a tiny amount of code since all you are doing is grabbing the port to connect from the configuration and returning a `dap.SocktTransport` from the `start` method.

https://github.com/daveleroy/sublime_debugger/tree/master/modules/adapters

**Comment by MetalSlime0** [comment]
Thanks. Is this something I would have to submit a pull request for or is there a place users could just copy the file?

**Comment by daveleroy** [comment]
You should be able to place a file in the `Packages` directory and it will be loaded

**Comment by MetalSlime0** [comment]
Great, thanks!
