### ISSUE TITLE
Split core UI code into separate library

### ISSUE THREAD

**Issue by imciner2** [daveleroy/sublime_debugger#28]
I really like the UI elements you have built up for the debug window, and I am thinking that I would like to build a nicer build view that uses some of them (such as the expandable items, so I can display errors/warnings nicer). I would prefer not to duplicate your work, and so I was wondering if you would consider moving the core UI elements to a new repository and doing a git subtree (unfortunately with package control you can't use submodules)  to include it in yours. Then I could reference them as well through that method. This might take some rearchitecting though, but I think it could be a really nice UI library for plugins to use.

**Comment by daveleroy** [comment]
I probably don't have the time to do this at the moment. Some things should probably be taken out of the core ui if it was to be split out and it relies on some of the other code as well.

Its really not as flexible as it seems you are pretty much stuck laying things out in rows which is why the debugger is split into multiple phantoms. Also the text doesn't wrap and its fairly slow.

**Comment by daveleroy** [comment]
I've actually been working a bit on getting the Default.exec command with the debugger. The idea is to have the output go into the debugger console and have the debugger wait until it completes before debugging begins.
