### ISSUE TITLE
Support RunInTerminalRequest

### ISSUE THREAD

**Issue by daveleroy** [daveleroy/sublime_debugger#35]

**Comment by barnabasjohnthomas** [comment]
Not sure if this is related, but if you put "${file}"
![Screen Shot 2019-08-22 at 11 34 49 AM](https://user-images.githubusercontent.com/47139855/63489925-0ace1e00-c4d1-11e9-83fb-bccbc7259843.png)
 in the 'program' field in the config file (instead of the full path), it doesn't run the Python file - it switches to the config file and says 

> name 'true' is not defined

I'm attaching the screenshot because I can't figure out how to copy text from the console.

**Comment by daveleroy** [comment]
Variables are getting evaluated when the debugger is opened or the settings updated so `${file}` usually won't reflect the current file (right now). In your case it looks like the debugger used the .sublime-project as the program

**Comment by barnabasjohnthomas** [comment]
So just restart the debugger?

**Comment by daveleroy** [comment]
I wouldn't use `${file}` until it gets fixed its going to have weird behavior. But yes I believe if you restart the debugger it will reevaluate `${file}` to the current one

**Comment by barnabasjohnthomas** [comment]
All right, cool!
