### ISSUE TITLE
Support for version information and update of adapters

### ISSUE THREAD

**Issue by erazor-de** [daveleroy/sublime_debugger#48]
At the moment supported adapters can be installed by clicking a menu item and an empty/full circle indicates if an adapter is installed.
To update an adapter to a newer version one needs to remove the folder from your plugins data/debug_adapters folder and reinstall it via the menu.
I would suggest showing the actual installed version of an adapter in the text of the according menu item, and a click on an already installed adapter should check and update the adapter if appropriate, maybe after an info dialog with version information. Alternatively the click could just remove and reinstall the adapter.
Also or instead an update command could be useful which updates or reinstalls all already installed adapters.

**Comment by daveleroy** [comment]
Adapters should be able to be reinstalled by installing them again. There was a bug on Windows where some (notable vscode-python) could not be deleted because it has files with really long paths which was fixed in 9a1881c54e5387916aaae7f92957b73d9ab5fcce but that isn't on package control.

Displaying the version should be fairly easy it can get extracted from the package.json file

I think checking for updates is probably more work than it's worth at this point. It would need to be done for both adapters downloaded from Microsoft and the ones that have platform specific implementations that need to be downloaded from Github releases.

**Comment by daveleroy** [comment]
https://github.com/daveleroy/sublime_debugger/commit/3a693cf2cd2ef7b8695ac06ca47650b79b5281cc now shows the version next to an installed adapter.

Maybe an `Update (reinstall) All Adapters` should be added that downloads and reinstalls all the ones you have installed
