### ISSUE TITLE
Question: How to debug sublime plugins with the debugger?

### ISSUE THREAD

**Issue by predragnikolic** [daveleroy/sublime_debugger#89]
I have always wondered how to debug ST plugins with this plugin. Has anyone tried this?

All I know is that ST runs all plugins on a separate process and that process runs an executable named plugin_host.
Do I just need to attach the debugger to that process? 

I haven't tried it, just wanted to see if anyone else had experimented with this.

**Comment by daveleroy** [comment]
I don't think it is currently possible since `debugpy` doesn't appear to work with Sublime's custom version of python. It's the same error that occurs here https://github.com/microsoft/debugpy/issues/334 so likely related.

Even if you could get `debugpy` working Sublime is going to lock up when you hit a breakpoint so you would need to run multiple instances.

**Comment by predragnikolic** [comment]
Forgot to thank you and close this issue when I saw your reply :)
